using System;

public static partial class Helpers
{
    public static string ToAscii(String hex)
    {
        switch (hex)
        {
            case "20":
                return " ";
            case "21":
                return "!";
            case "22":
                return "\"";
            case "23":
                return "#";
            case "24":
                return "$";
            case "25":
                return "%";
            case "26":
                return "&";
            case "27":
                return "'";
            case "28":
                return "(";
            case "29":
                return ")";
            case "2a":
                return "*";
            case "2b":
                return "+";
            case "2c":
                return ",";
            case "2d":
                return "-";
            case "2e":
                return ".";
            case "2f":
                return "/";
            case "30":
                return "0";
            case "31":
                return "1";
            case "32":
                return "2";
            case "33":
                return "3";
            case "34":
                return "4";
            case "35":
                return "5";
            case "36":
                return "6";
            case "37":
                return "7";
            case "38":
                return "8";
            case "39":
                return "9";
            case "3a":
                return ":";
            case "3b":
                return ";";
            case "3c":
                return "<";
            case "3d":
                return "=";
            case "3e":
                return ">";
            case "3f":
                return "?";
            case "40":
                return "@";
            case "41":
                return "A";
            case "42":
                return "B";
            case "43":
                return "C";
            case "44":
                return "D";
            case "45":
                return "E";
            case "46":
                return "F";
            case "47":
                return "G";
            case "48":
                return "H";
            case "49":
                return "I";
            case "4a":
                return "J";
            case "4b":
                return "K";
            case "4c":
                return "L";
            case "4d":
                return "M";
            case "4e":
                return "N";
            case "4f":
                return "O";
            case "50":
                return "P";
            case "51":
                return "Q";
            case "52":
                return "R";
            case "53":
                return "S";
            case "54":
                return "T";
            case "55":
                return "U";
            case "56":
                return "V";
            case "57":
                return "W";
            case "58":
                return "X";
            case "59":
                return "Y";
            case "5a":
                return "Z";
            case "5b":
                return "[";
            case "5c":
                return "\\";
            case "5d":
                return "]";
            case "5e":
                return "^";
            case "5f":
                return "_";
            case "60":
                return "`";
            case "61":
                return "a";
            case "62":
                return "b";
            case "63":
                return "c";
            case "64":
                return "d";
            case "65":
                return "e";
            case "66":
                return "f";
            case "67":
                return "g";
            case "68":
                return "h";
            case "69":
                return "i";
            case "6a":
                return "j";
            case "6b":
                return "k";
            case "6c":
                return "l";
            case "6d":
                return "m";
            case "6e":
                return "n";
            case "6f":
                return "o";
            case "70":
                return "p";
            case "71":
                return "q";
            case "72":
                return "r";
            case "73":
                return "s";
            case "74":
                return "t";
            case "75":
                return "u";
            case "76":
                return "v";
            case "77":
                return "w";
            case "78":
                return "x";
            case "79":
                return "y";
            case "7a":
                return "z";
            default:
                return "";
        }
    }
}